### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by VishnuMNair** [Equidamoid/dltpy#2]
Is it possible to give support for this package in windows?

Please help!

**Comment by Equidamoid** [comment]
Hi!

There is a bit of a problem: I don't have access to any windows machines, even at work, so I can't really do anything with a windows build.

I would still really appreciate a pull request =). 

AFAIR there is nothing in the code that prevents a windows build. Tha main challenge would be to build boost:python and make cmake happy with it.

**Comment by VishnuMNair** [comment]
Hi,

I hve boost setup and cmake for windows. I can create a visual studio project out of it and build from there. I’m getting errors for headers like unistd, If I’m able to resolve it I’ll update.

**Comment by Equidamoid** [comment]
I just checked, and includes of `fcntl.h` and `unistd.h` seem unused in dltreader.cpp, you can just kill them.

**Comment by VishnuMNair** [comment]
Hi,

Getting below issue,
 cannot convert from 'std::_Array_iterator<_Ty,8196>' to 'char *'

any thoughts?

**Comment by Equidamoid** [comment]
Could you please copypaste **full** error message? It's hard to guess where exactly it goes wrong.

**Comment by VishnuMNair** [comment]
getting error on 

`std::array<char, 8196> iBuffer;
    char* iDataEnd{iBuffer.begin()};
    char* iCursor{iBuffer.begin()};
    char* iMessageBegin{iBuffer.begin()};`

all iBuffer related operations giving same issue
` std::tuple<char*, size_t> getBuffer(){flush(); return {iDataEnd, iBuffer.end() - iDataEnd};}`

![dlt](https://user-images.githubusercontent.com/24523632/69398707-68ad1480-0d11-11ea-8b73-e2f42aa44091.PNG)

**Comment by Equidamoid** [comment]
Ah, now I see, could you try replacing `begin` with `data` in places where
it is casted to `char*`?

**Comment by VishnuMNair** [comment]
`end`  also?

**Comment by VishnuMNair** [comment]
getting below error also
![dlt2](https://user-images.githubusercontent.com/24523632/69426517-71bed580-0d53-11ea-9401-2445752cd3d1.PNG)

**Comment by VishnuMNair** [comment]
Any update??

**Comment by Equidamoid** [comment]
Well, I still can't reproduce the problem locally (and the new one too). Neither gcc with bunch of `-W...` and `-pedantic`, nor clang-tidy (portability, cppcoreguidelines, bugprone) showed any similar warnings. 

I'll try a bit more.

If you manage to fix it, a pullrequest will be appreciated =)

**Comment by Equidamoid** [comment]
In the meantime, which version of the compiler are you using?

**Comment by Equidamoid** [comment]
Okay, one more idea: [apparently](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners) github actions support windows runners. 

Could you try to reproduce it on a runner? To make life easier I recently got rid of boost dependency. And fmt can be easily used from a submodule.

**Comment by rettenbs** [comment]
I got the module to compile and link on Windows. However, I am still struggling with installing the module. This is the error I get from `pip install --user -e dltpy`:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\v043419\workspace\software\dltpy\setup.py", line 54, in <module>
        setup(
      File "c:\program files\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python38\lib\site-packages\setuptools\command\develop.py", line 38, in run
        self.install_for_development()
      File "c:\program files\python38\lib\site-packages\setuptools\command\develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "c:\program files\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\v043419\workspace\software\dltpy\setup.py", line 22, in run
        super().run()
      File "c:\program files\python38\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "c:\program files\python38\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\program files\python38\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\program files\python38\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\program files\python38\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\program files\python38\lib\distutils\command\build_ext.py", line 550, in build_extension
        self.compiler.link_shared_object(
      File "c:\program files\python38\lib\distutils\ccompiler.py", line 713, in link_shared_object
        self.link(CCompiler.SHARED_OBJECT, objects,
      File "c:\program files\python38\lib\distutils\_msvccompiler.py", line 516, in link
        build_temp = os.path.dirname(objects[0])
    IndexError: list index out of range
```

Any idea?

**Comment by rettenbs** [comment]
I managed to get in running: https://github.com/Equidamoid/dltpy/pull/4
It would be nice if you could create wheels for PyPi so nobody else has to go through the complex setup to install the module.

**Comment by Equidamoid** [comment]
@rettenbs good job! Thanks!

Regarding the wheels, it might be a good idea, especially for windows. But probably you can guess my problem here...
It would be cool if you could help with setting up a build for it (also, it will prevent me from breaking windows builds in the future :D)
